---
- name: clone shadowsocks repo
  git:
    repo: https://github.com/glzjin/shadowsocks.git
    dest: /usr/local/shadowsocks
    version: manyuser
  notify:
    start shadowsocks service

- name: add runable promise to server python file
  file:
    path: /usr/local/shadowsocks/server.py
    mode: 777
    