- name: install docker-ce
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
  when: ansible_os_family == "RedHat"
  notify:
    enable and start docker

- name: install docker-ce
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - docker-ce
  when: ansible_os_family == "Debian"
  notify:
    enable and start docker

- name: install docker-py
  command: pip install docker-py
