---
galaxy_info:
  author: Indeyxz
  description: Quick setup docker
  min_ansible_version: 0.0.0
  license: MIT
  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions: any
  categories:
    - docker

dependencies: []


