---

- name: setup build env in centos
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - curl-devel
    - expat-devel
    - gettext-devel
    - openssl-devel
    - zlib-devel 
    - perl-devel
  when: ansible_os_family == "RedHat"